### ISSUE TITLE
PCB Review

### ISSUE THREAD

**Issue by rodneyosodo** [SammyOina/stewart-platform#5]
# 
![Screenshot from 2022-08-24 15-43-25](https://user-images.githubusercontent.com/28790446/186422255-f87652d3-38ab-4aac-a0b1-dd23ac016be4.png)

- I'd suggest you have the via diameter equal to track width
- Increase clearance for Default
- Check on minimum clearance and minimum via diameter from JLCPCB

# 
![Screenshot from 2022-08-24 15-42-26](https://user-images.githubusercontent.com/28790446/186422279-030e6552-edb5-4152-b5cb-ce158c8f206f.png)

- You can use smd diode, resisitor and also capacitor

#
![Screenshot from 2022-08-24 15-42-08](https://user-images.githubusercontent.com/28790446/186422288-3545ad40-92a6-4040-8c9f-4c6adeb072ca.png)

- you can place the MCU in the middle and add a ground plane beneath it or even remove PCB so as it has a huge hole

#
![Screenshot from 2022-08-24 15-40-05](https://user-images.githubusercontent.com/28790446/186422309-8330d09e-9b3d-4f87-8cf2-96757f763b0d.png)

- What are these for?

#
![Screenshot from 2022-08-24 15-38-34](https://user-images.githubusercontent.com/28790446/186422322-8519adb9-3ff3-4b39-85e5-cf5193cdf158.png)

- Align the net labels and names
#
![Screenshot from 2022-08-24 15-37-54](https://user-images.githubusercontent.com/28790446/186422351-ecf1575f-192d-4670-877d-a2686a601721.png)

- you can add a bulk capacitor
#
![Screenshot from 2022-08-24 15-37-34](https://user-images.githubusercontent.com/28790446/186422380-bfecdc8d-29a8-45c3-9039-c2aa51465bce.png)

- Do you need this because your connector is JST and it only goes one way or which connector are you using?
- Don't you need a resistor

**Comment by SammyOina** [comment]
"you can place the MCU in the middle and add a ground plane beneath it or even remove PCB so as it has a huge hole"
Didn't want to interfere with the antenna, does the ground plane beneath the MCU interfere with signals @0x6f736f646f

**Comment by SammyOina** [comment]
Do you need this because your connector is JST and it only goes one way or which connector are you using?
Don't you need a resistor

I'll get rid of it cause I'm using JST

**Comment by SammyOina** [comment]
You can use smd diode, resisitor and also capacitor

only the diode is not smt

**Comment by SammyOina** [comment]
you can add a bulk capacitor

is it necessary @0x6f736f646f  cause I have some capacitors on the buck converter

**Comment by SammyOina** [comment]
What are these for?

the i2c bus is just for extra I/O

**Comment by rodneyosodo** [comment]
> "you can place the MCU in the middle and add a ground plane beneath it or even remove PCB so as it has a huge hole" Didn't want to interfere with the antenna, does the ground plane beneath the MCU interfere with signals @0x6f736f646f

No. If they are signal wires underneath yes.

**Comment by rodneyosodo** [comment]
> You can use smd diode, resisitor and also capacitor
> 
> only the diode is not smt

How so? What diode is it?

**Comment by rodneyosodo** [comment]
> you can add a bulk capacitor
> 
> is it necessary @0x6f736f646f cause I have some capacitors on the buck converter

Not necessary but a good enhancement

**Comment by rodneyosodo** [comment]
> What are these for?
> 
> the i2c bus is just for extra I/O

Why not one?

**Comment by SammyOina** [comment]
> > "you can place the MCU in the middle and add a ground plane beneath it or even remove PCB so as it has a huge hole" Didn't want to interfere with the antenna, does the ground plane beneath the MCU interfere with signals @0x6f736f646f
> 
> No. If they are signal wires underneath yes.

In that case I'll just leave it there

**Comment by SammyOina** [comment]
> > You can use smd diode, resisitor and also capacitor
> > only the diode is not smt
> 
> How so? What diode is it?

the diode was 1N5822 I have replaced it with SS34 in https://github.com/SammyOina/stewart-platform/commit/a19fa3e659def1261903ad4870dcb75b86429917

**Comment by SammyOina** [comment]
> > you can add a bulk capacitor
> > is it necessary @0x6f736f646f cause I have some capacitors on the buck converter
> 
> Not necessary but a good enhancement

any suggestion on suitable capacitance

**Comment by SammyOina** [comment]
> > What are these for?
> > the i2c bus is just for extra I/O
> 
> Why not one?

Just a redundancy now removed in https://github.com/SammyOina/stewart-platform/commit/86757a8a3ff919bb4a3457589e3a49e60fa6ca65

**Comment by rodneyosodo** [comment]
> > > "you can place the MCU in the middle and add a ground plane beneath it or even remove PCB so as it has a huge hole" Didn't want to interfere with the antenna, does the ground plane beneath the MCU interfere with signals @0x6f736f646f
> > 
> > 
> > No. If they are signal wires underneath yes.
> 
> In that case I'll just leave it there

You can place it at the centre of one of the edges

**Comment by rodneyosodo** [comment]
> > > you can add a bulk capacitor
> > > is it necessary @0x6f736f646f cause I have some capacitors on the buck converter
> > 
> > 
> > Not necessary but a good enhancement
> 
> any suggestion on suitable capacitance

470uF

**Comment by rodneyosodo** [comment]
Add mounting holes on the PCB

**Comment by SammyOina** [comment]
> Add mounting holes on the PCB

I'll add that as well as silk screens before making the order, just wanted to ensure functionality

**Comment by SammyOina** [comment]
> > > > "you can place the MCU in the middle and add a ground plane beneath it or even remove PCB so as it has a huge hole" Didn't want to interfere with the antenna, does the ground plane beneath the MCU interfere with signals @0x6f736f646f
> > > 
> > > 
> > > No. If they are signal wires underneath yes.
> > 
> > 
> > In that case I'll just leave it there
> 
> You can place it at the centre of one of the edges

It's in that position just cause of routing but I'll optimize and try to move it before making the order

**Comment by rodneyosodo** [comment]
> > Add mounting holes on the PCB
> 
> I'll add that as well as silk screens before making the order, just wanted to ensure functionality

Isn't silk screen already added?

**Comment by SammyOina** [comment]
> > > Add mounting holes on the PCB
> > 
> > 
> > I'll add that as well as silk screens before making the order, just wanted to ensure functionality
> 
> Isn't silk screen already added?

Yes, Just editing them and making sure everything is in place, which is now done
