### ISSUE TITLE
Ground and power connections.

### ISSUE THREAD

**Issue by kimanimichael** [SammyOina/stewart-platform#7]
![Screenshot from 2022-08-29 19-23-46](https://user-images.githubusercontent.com/49106674/187248863-13b9f5f6-0987-4e72-8b4a-1a2932185884.png)

Any reason for introducing the above inconsistency? If not, I'd advise you maintain the conventional ground symbol.

Also I'd advise to maintain all power connections as you have done above for the 12V. Makes reviewing easier.

**Comment by SammyOina** [comment]
It's just included the Net port and net flag just for the appearance as they fit in some connections aesthetically, otherwise I agree on the point about consistency
